// Generated by yaCCM
// File function.hpp

#ifndef _FUNCTION_HPP_
#define _FUNCTION_HPP_

#include "yaCCM_runtime.hpp"

//START_0a17621452b6cbbb8da68b5c0818e96526462aa02d00ca65d22b0ff7
//STOP

virtual void activate ()=0;
virtual int plus (long left , long right)=0;
virtual void inc (long& val)=0;
virtual void zero (long& val)=0;

#endif // _FUNCTION_HPP_