// Generated by yaCCM
// File include.hpp

#ifndef _INCLUDE_HPP_
#define _INCLUDE_HPP_

#include "yaCCM_runtime.hpp"

//START_0739edb665236457615b5f5f15502b5b06a623b4ede28795b373b9b8
//STOP

#include "toto.hpp"

#include "titi.hpp"

typedef float speed;

typedef int myInt_2;

typedef ::MCCM::Boolean myBoolean;


#endif // _INCLUDE_HPP_