// Generated by yaCCM
// File interface.hpp

#ifndef _INTERFACE_HPP_
#define _INTERFACE_HPP_

#include "yaCCM_runtime.hpp"

//START_432094a6f1093bd5e28aaff7ffec91ea08ffb15906946acb3189c560
//STOP

namespace Boids_Interface {
	class iService {
		public:
			iService() {};
			virtual ~iService() {};
		virtual int functionWith1Arg (MyInt val)=0;
		virtual int functionWith2Args (MyInt arg1 , float& arg2)=0;
	};
	
	//START_63d1aec4945fb5de5a936076481c5637779bf99fd01bd15c71396091
	//STOP
};



#endif // _INTERFACE_HPP_