// Generated by yaCCM
// File qualified_symbol.hpp

#ifndef _QUALIFIED_SYMBOL_HPP_
#define _QUALIFIED_SYMBOL_HPP_

#include "yaCCM_runtime.hpp"

//START_bd5b895b7be2bb466913b5af9bf8b6a915d6fa5b31f7d161b7bdc7f1
//STOP

typedef ::MCCM::truc myBoolean;


#endif // _QUALIFIED_SYMBOL_HPP_